pipeline {
  agent any
  tools {nodejs "NodeJs"}
  stages {
    stage('Clone Repo') {
      steps{
        git credentialsId: 'f00ff383-c25e-4332-8f82-0a153badb25a', url: 'git@github.com:wizeline/wizeline-sre-opeyemi-alao.git'
      }
    }
    stage('Install dependencies') {
      steps {
        dir("cidr_convert_api/node") {
          sh "pwd"
          sh 'npm install'
        }
      }
    }
    stage('Test') {
      steps {
        dir("cidr_convert_api/node") {
          sh 'npm test'
        }
      }
    } 
    stage() {
    if (currentBuild.result == 'FAILURE') {
      error("Aborting the Pipeline, one or more test failed")
      return
    }
    }
    stage('Docker Build') {
      steps {
        dir("cidr_convert_api/node") {
          sh '''
              docker build -t opeyemi-alao:THT .
              docker tag opeyemi-alao:THT wizelinedevops/opeyemi-alao:THT
             '''
        }
      }
    }
  }
}
